namespace = "testonly"
PublicIP = "0.0.0.0"
Port = 0
StoragePath = "somewhereundertherainbow"
BootstrapOnly = false

TracingSystem = "elastic"
NotaryGroupConfig = "./ng.toml"
Gossip3NotaryGroupConfig = "./g3ng.toml"

[PrivateKeySet]
SignKeyHex = "0x4344e3372f1b790016ed86400611fab64d0bba91136518685a7ce34106f1c759"
DestKeyHex = "0xc09363e85290020c132053f029f23988d4e35c521b0698312e0071f3e5d0e023"

