on: release
name: Docker Build & Push Latest
jobs:
  docker:
    name: "docker build & push latest"
    runs-on: ubuntu-18.04
    env:
      # ${{ runner.workspace }} is not available here, so hardcode for now
      # setup-go is considering inject these env vars automatically
      GOPATH: /home/runner/work/tupelo/go
      GOBIN: /home/runner/work/tupelo/go/bin
    steps:
    - name: install go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler make
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      id: vendor-cache
      with:
        path: vendor/
        key: go-vendor-${{ hashFiles('go.sum') }}
        restore-keys: |
          go-vendor-
    - name: git setup
      run: scripts/ci-gitsetup.sh
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: vendor dependencies
      if: steps.vendor-cache.outputs.cache-hit != 'true'
      run: make vendor
    - name: run tests
      run: scripts/test-suite.sh
    - name: set version
      run: make github-prepare
      env:
        GITHUB_REF: ${{ github.ref }}
    - name: docker login
      run: docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: docker build and push
      run: |
        docker build -t quorumcontrol/tupelo:latest .
        docker push quorumcontrol/tupelo:latest